spring.application.name=Review-MicroService
server.port=8083
# Database configuration
#spring.datasource.url=jdbc:h2:mem:test
spring.datasource.url=jdbc:postgresql://localhost:5432/reviewdb
spring.datasource.username=postgres
spring.datasource.password=saso@2005
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Eureka configuration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.healthcheck.enabled=true
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30

